language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '11'
script:
  npm run semantic-release
  # - npm run test
  # - npm run build
  # - npm run jsdoc
  # - npm run toc
# after_success:
  # - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
git:
  submodules: false
